version: 2.1

parameters:
  package_branch:
    type: string
    default: "null"
  package_url:
    type: string
    default: "null"
  sha:
    type: string
    default: "null"
  project:
    type: string
    default: "null"
  pull_req_id:
    type: string
    default: "null"
  body:
    type: string
    default: "null"

jobs:
  build:
    docker:
      - image: cimg/base:stable

    steps:
      - setup_remote_docker:
          version: 19.03.14
          docker_layer_caching: true

      - run:
          name: 'This Build: << pipeline.parameters.project >> branch: <<pipeline.parameters.package_branch>> PR id: <<pipeline.parameters.pull_req_id>>'
          command: 'echo <<pipeline.parameters.package_url>>'

      - run:
          name: 'clone pm4core-docker'
          command: 'git clone --depth 1 https://github.com/ProcessMaker/pm4core-docker.git -b v2 .'

      - run:
          name: 'build the local cicd image and run tests'
          command: |
            source set_context_example.sh
            export GITHUB_TOKEN=$GIT_TOKEN
            docker-compose run cicd

# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build:
    jobs:
      - build
#